# Generated by Django 5.0.4 on 2024-04-27 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='arq',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
