# Generated by Django 5.0.4 on 2024-04-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0002_art_arq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='arq',
            field=models.ImageField(upload_to='data/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
